**hiring.csv** \
This file contains hiring statics for a firm such as experience of candidate,\
his written test score and personal interview score. Based on these 3 factors, \
HR will decide the salary. Given this data, you need to build a machine learning \
model for HR department that can help them decide salaries for future candidates. \ 
Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [61]:
hiring = pd.read_csv("hiring.csv")

In [62]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [63]:
hiring.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [64]:
hiring.rename(columns={'test_score(out of 10)': 'test_score'}, inplace=True)
hiring.rename(columns={'interview_score(out of 10)': 'interview_score'}, inplace=True)
hiring.rename(columns={'salary($)': 'salary'}, inplace=True)
hiring

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [67]:
hiring.test_score = hiring.test_score.fillna(hiring.test_score.median())
hiring.experience = hiring.experience.fillna('zero')
hiring

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [68]:
for i in range(len(hiring.index)):
    hiring.experience[i] = w2n.word_to_num(hiring.experience[i])
    i = i + 1

C:\Users\sunam\AppData\Local\Temp\ipykernel_12448\1064072709.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hiring.experience[i] = w2n.word_to_num(hiring.experience[i])


In [69]:
hiring.experience = hiring.experience.replace(0, hiring.experience.median())

In [70]:
reg = linear_model.LinearRegression()

In [71]:
reg.fit(hiring[['experience','test_score','interview_score']],hiring.salary)

LinearRegression()

In [72]:
reg.coef_

array([3390.87422644, 1803.45158198, 3184.69450013])

In [73]:
reg.intercept_

4220.8228013597545

In [74]:
reg.predict([[2,9,6]])

C:\Users\sunam\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46341.80249281])

In [75]:
reg.predict([[12,10,10]])

C:\Users\sunam\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94792.77433975])