In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
area  = df.area
prices = df.price

In [5]:
model = LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

C:\Users\sunam\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

### Save File

In [1]:
import pickle

In [9]:
with open('model_pickel','wb') as f:
    pickle.dump(model,f)

In [10]:
with open('model_pickel','rb') as f:
    mp = pickle.load(f)

In [12]:
mp .predict([[5000]])

C:\Users\sunam\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

### Joblib to Save File
If model consists of large numpy array, then Joblib tends to be more efficient

In [17]:
import joblib

In [18]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
mj = joblib.load('model_joblib')

In [21]:
mj.predict([[5000]])

C:\Users\sunam\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])